package Problem;

class Solution_16 {
    public int diagonalSum(int[][] mat) {
        int size = mat.length;
        int result = 0;
        for (int i = 0; i < size; i++) {
            for (int j = 0; j < size; j++) {
                if (i == j || i == (size - j - 1)) {
                    result += mat[i][j];
                } 
            }
        }

        // Generated by AI
        // for (int i = 0; i < size; i++) {
        //     result += mat[i][i];
        //     result += mat[i][size - 1 - i];
        // }
        // result -=mat[size / 2][size / 2];
        return result;
    }
}

public class P16E_Array_L1572 {
    public static void main(String[] args) {
        int[][] mat = { { 1,2,3 }, { 4,5,6 }, { 7,8,9 } };
        System.out.println(new Solution_16().diagonalSum(mat));
    }
}
